trigger:
  branches:
    include:
      - main

variables:
  buildConfiguration: 'Release'

jobs:
# JOB 1: Provisiona recursos Azure (RG, SQL Server, DB, WebApp)
- job: ProvisionarInfraSkill4Green
  displayName: 'Provisionar Infraestrutura Skill4Green'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: AzureCLI@2
    displayName: 'Provisionar Web App e Database atualizado na nuvem'
    inputs:
      azureSubscription: 'MyAzureSubscription'
      scriptType: 'bash'
      scriptLocation: 'scriptPath'
      scriptPath: 'scripts/script-infra-provisionamento.sh'
    env:
      SQL_SERVER: $(SQL_SERVER)
      SQL_ADMIN: $(SQL_ADMIN)
      SQL_PASSWORD: $(SQL_PASSWORD)
      SQL_DB: $(SQL_DB)
      WEBAPP_NAME: $(WEBAPP_NAME)

# JOB 2: Compila, testa e gera artefato da Skill4Green API
- job: BuildTestPublicarSkill4Green
  displayName: 'Build, Test e Publish do Projeto Skill4Green'
  dependsOn: ProvisionarInfraSkill4Green
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: UseDotNet@2
    displayName: 'Instalar .NET SDK'
    inputs:
      packageType: 'sdk'
      version: '9.x'

  - task: DotNetCoreCLI@2
    displayName: 'Restaurar dependências do projeto'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'Compilar projeto Skill4Green'
    inputs:
      command: 'build'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'Executar testes automatizados com XUnit'
    inputs:
      command: 'test'
      projects: '**/*Tests.csproj'
      arguments: '--configuration $(buildConfiguration) --logger "trx;LogFileName=test-results.trx"'
      publishTestResults: true

  - task: PublishTestResults@2
    displayName: 'Publicar resultados dos testes'
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '**/*.trx'
      failTaskOnFailedTests: true

  - task: DotNetCoreCLI@2
    displayName: 'Gerar artefato da Skill4Green API'
    inputs:
      command: 'publish'
      publishWebProjects: true
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publicar artefato para Release'
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'skill4green-api'