-- Criação da tabela Pontuacoes
CREATE TABLE Pontuacoes (
    Id NUMBER(10) GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    Nome NVARCHAR2(2000) NOT NULL,
    EcoCoins NUMBER(10) NOT NULL,
    NivelVerde NUMBER(10) NOT NULL,
    AtualizadoEm TIMESTAMP(7) NOT NULL
);

-- Criação da tabela Recompensas
CREATE TABLE Recompensas (
    Id NUMBER(10) GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    Nome NVARCHAR2(2000) NOT NULL,
    CustoEcoCoins NUMBER(10) NOT NULL,
    Tipo NVARCHAR2(2000) NOT NULL
);